### ISSUE TITLE
Empty char `''` is not syntactically valid

### ISSUE THREAD

**Issue by brekk** [madlib-lang/madlib#129]
```
import List from "List"
import Maybe from "Maybe"

FRAMESET = [' ', '▁', '▃', '▄', '▅', '▆', '▇']
FRAMES = pipe(
  List.range(0),
  List.reduce(
    (agg, x) => pipe(
      List.nth($, FRAMESET),
      Maybe.fromMaybe(''),
    )(x),
    [],
  ),
)(10)
```

In the `fromMaybe` above, an empty char isn't valid, but the error points at the final parentheses rather than the second single quote.

It would be awesome (and better DX) to have Madlib tell me what I did wrong on the second single quote (or similar)

**Comment by aboeglin** [comment]
Closed by #132
