### ISSUE TITLE
`of` / `pure` calls are implicit / not importable

### ISSUE THREAD

**Issue by brekk** [madlib-lang/madlib#130]
```
import Wish from "Wish"

pipe(
  Wish.fulfill(
    (e) => { IO.trace("error", e) },
    (x) => { IO.trace("success", x) },
  )
)(Wish.of("cool"))
```

☝🏼 The above is incorrect because `Wish` doesn't have an explicit `of`, instead `of` is an instance method. But this is an easy footgun if you're not paying attention.

Ideally the fix is either:
- add something like `Wish.of` or some other pure alias
- a more explicit error which indicates to the user what the mistake is

**Comment by aboeglin** [comment]
Fixed with the second proposal for now, closing this as it's released in #132.
