### ISSUE TITLE
Nullary functions

### ISSUE THREAD

**Issue by aboeglin** [madlib-lang/madlib#14]
Investigate and see how we could implement nullary functions, and how they would be typed. We’d probably need a Void type that is only valid for unary functions as the parameter. Effectively making it a nullary.

**Comment by brekk** [comment]
ooooh those porpoises are smooth!

**Comment by aboeglin** [comment]
Potential solution would be to have a sort of syntax sugar for such cases such that:
```madlib
() => x
```

is inferred as:
```madlib
() -> a
```

And:
```madlib
fn()
```
is desugared as:
```madlib
fn(()) // <- we pass that extra unit here
```

**Comment by brekk** [comment]
This can be closed, the feature was added to Madlib in `v.0.13.0` — https://github.com/madlib-lang/madlib/releases/tag/v0.13.0
