### ISSUE TITLE
Inconsistent behavior between targets

### ISSUE THREAD

**Issue by brekk** [madlib-lang/madlib#149]
```
import IO from "IO"

printInt = (max) => {
  i = 0
  subcheck = () => {
    IO.trace("iter", i)
    i := i + 1
    return if (i < max) {
      subcheck()
    } else {
      i
    }
  }
  return subcheck()
}

main = () => {
  pipe(
    printInt,
    IO.trace("print?!?!"),
  )(300)
}
```

☝🏼 This is some dumb code but in JS mode it runs and prints the `"iter"` statement 300 times. With `--target llvm` on, it prints only a single time.

Additionally in LLVM mode it prints an integer which is outside the range of 0 - 300 (4341403600 is an example but it's not consistent between re-runs)

**Comment by aboeglin** [comment]
Solved in 0.23.5.
