### ISSUE TITLE
Future feature: support markdown in documentation blocks

### ISSUE THREAD

**Issue by brekk** [madlib-lang/madlib#15]
Relative to [this comment](https://github.com/madlib-lang/madlib/pull/13#discussion_r605149437), it would be nice to support markdown formatting in doc-blocks.

**Comment by aboeglin** [comment]
Sounds good. I would move that to the repository of MadDoc though. As the compiler already does it I believe. It should take whatever you put in there. So it's mainly a display problem I think.

**Comment by brekk** [comment]
Moved to maddoc
