### ISSUE TITLE
String expressions in template strings should not show quotes

### ISSUE THREAD

**Issue by aboeglin** [madlib-lang/madlib#162]
```madlib
import IO from "IO"



main = () => {
  IO.put(`yo yo yo hey nice ${"k"}`)
}
```

The above should not print the two double quotes around k.

To do this I think we need to strip double quotes from normal string literals either straight in the lexer or during canonicalization and also stop stripping them at codegen. Then we should always have the right behavior. Luckily it seems we have enough tests covering these so it should be easy to try out.

**Comment by brekk** [comment]
In my testing / estimation this issue can be closed
