### ISSUE TITLE
Valid escaped string results in `madlib: Prelude.read: no parse`

### ISSUE THREAD

**Issue by brekk** [madlib-lang/madlib#23]
Using escape sequences which should be valid instead cause the compiler to barf in a non-clear way:

```
export ch = {
  q: '\''
}
```

Throws an error:
```
madlib: Prelude.read: no parse
```
With no additional context.

However, this can be mitigated by using backticks instead (but you can also run into a [different error](https://github.com/madlib-lang/madlib/issues/22) as described there), like so:

```
export ch = {
  q: `'`
}
```
Also valid:
```
export ch = {
  q: "'"
}
```

**Comment by aboeglin** [comment]
fixed by #13
