### ISSUE TITLE
Translate number to string

### ISSUE THREAD

**Issue by gavr123456789** [madlib-lang/madlib#68]
Cant find a way to translate number to string.  
Also prettyPrint which I found in docs not exported:  
`The default import 'IO' does not export the function 'prettyPrint'.`

**Comment by gavr123456789** [comment]
There are fromString in Number, but there no fromNumber in String

**Comment by aboeglin** [comment]
That still needs documentation. If you’re familiar with Show in Haskell you have Inspect in Madlib. It’s defined for all types and automatically derived for user types. IO.log does it for you so that you can print anything in Madlib.

**Comment by aboeglin** [comment]
There’s also Show but that must be defined by users.

**Comment by gavr123456789** [comment]
Wait, can you give an example

**Comment by aboeglin** [comment]
Sure:

`inspect(3)` gives you `"3"`.
`IO.log(3)` prints `3`.

log being defined like this:
```
log :: Inspect a => a -> {}
export log = pipe(inspect, putLine)
```

`{}` is the unit type and uses the same notation for the value. It can be thought of as the empty record.

**Comment by aboeglin** [comment]
Also like I said above, all built-in types implement Inspect, and user defined types have an instance for Inspect automatically defined as it compiles. The same goes for Eq where the method is `==`.

**Comment by aboeglin** [comment]
> Also prettyPrint which I found in docs not exported:
> `The default import 'IO' does not export the function 'prettyPrint'.`
 
 Docs aren’t up to date, the best for now would be to look in the folder `prelude/__internal__`. PrettyPrint will come back soon now that the standard library includes a parser combinator library as well as a pretty printing library ( currently used for json parsing/printing ).

**Comment by gavr123456789** [comment]
Thanks!
